version: '3'
services:
  mongo:
    image: mongo
    networks:
      - blog-rede
    container_name: mongo

  api:
    build:
      dockerfile: ./api/Dockerfile
      context: .
    image: feliperegino/blog-node-api
    container_name: blog
    ports:
      - "3000"
    networks:
      - blog-rede
    depends_on:
      - "mongo"

  client:
    build:
      dockerfile: ./client/Dockerfile
      context: .
    image: feliperegino/blog-node-client
    container_name: client
    ports:
      - "8000:8000"
    networks:
      - blog-rede
    depends_on:
      - "api"

networks:
  blog-rede:
    driver: bridge